Repository prgrms-fe-devcourse/NFE1_2_FitPlace, pull requests merged in 2024-09, with the labels that each got.

#2 [chore]Test
  .github/.gitmessage.txt
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
Labels: 환경설정

#14 [Design] 초기 레이아웃 지정 및 Router
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/Mainpage.tsx
  tailwind.config.js
  yarn.lock
Labels: 퍼블리싱, 환경설정

#16 feature: 카카오 지도 맵 및 마커 표시 기능 구현
  src/App.tsx
  src/KakaoMap.tsx
Labels: 기능구현

#26 [Degisn]로그인/회원가입 퍼블리싱
  src/App.tsx
  src/components/Button.tsx
  src/components/RegisterInput.tsx
  src/pages/register/Login.tsx
  src/pages/register/Register.tsx
  tailwind.config.js
Labels: 퍼블리싱

#25 [Design]메인페이지 퍼블리싱
  src/App.tsx
  src/assets/FitPlaceLogo.svg
  src/assets/Search.svg
  src/assets/notifications.svg
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/Health_post.tsx
  src/components/Popular_sports.tsx
  src/components/Search_bar.tsx
  src/pages/Mainpage.tsx
Labels: 퍼블리싱

#30 design: 위치 설정페이지 퍼블리싱
  src/pages/LocationSetting.tsx
Labels: 퍼블리싱

#31 [Fix] Git 충돌 오류 해결
  src/App.tsx
  src/pages/KakaoMap.tsx
  src/pages/LocationSetting.tsx
  src/pages/Mainpage.tsx
  src/pages/Ranking_page.tsx
  src/pages/register/Login.tsx
  src/pages/register/Register.tsx
Labels: 오류수정

#34 Design/#22
  index.html
  src/App.tsx
  src/assets/icon_user_profile.svg
  src/components/Button.tsx
  src/components/Health_post.tsx
  src/components/PostItem.tsx
  src/components/SearchPost.tsx
  src/components/SearchUser.tsx
  src/components/SearchUser_item.tsx
  src/components/Search_bar.tsx
  src/main.tsx
  src/pages/Mainpage.tsx
  src/pages/SearchPage.tsx
  tailwind.config.js
Labels: 퍼블리싱

#35 [Design]게시글 생성페이지 퍼블리싱
  .DS_Store
  src/.DS_Store
  src/App.css
  src/App.tsx
  src/assets/.DS_Store
  src/assets/arrowforward.svg
  src/components/Button.tsx
  src/pages/NotionAdd.tsx
Labels: 퍼블리싱

#37 Design/#33/프로필 페이지 퍼블리싱
  src/App.tsx
  src/assets/LinkIcon.svg
  src/assets/check.svg
  src/assets/defaultProfileImg.svg
  src/components/ProfileWrap.tsx
  src/data/location.ts
  src/pages/profile/ProfileDesc.tsx
  src/pages/profile/ProfileEdit.tsx
  src/pages/profile/ProfileImg.tsx
  src/pages/profile/ProfileLocation.tsx
  src/pages/profile/ProfileNickname.tsx
  src/pages/profile/ProfileTemplate.tsx
  tailwind.config.js
Labels: 퍼블리싱

#39 design: 알림 페이지 퍼블리싱
  src/App.tsx
  src/components/NotificationItem.tsx
  src/pages/LocationSetting.tsx
  src/pages/NotificationPage.tsx
  yarn.lock
Labels: 퍼블리싱

#40 [Design]Navbar / Ranking 페이지 퍼블리
  .DS_Store
  index.html
  src/.DS_Store
  src/App.tsx
  src/assets/.DS_Store
  src/assets/Ranking/Ranking_bg.jpg
  src/assets/Ranking/Ranking_title.svg
  src/assets/Ranking/Testimg.svg
  src/assets/navbar/Home.svg
  src/assets/navbar/My.svg
  src/assets/navbar/Ranking.svg
  src/assets/navbar/Search.svg
  src/assets/navbar/newPost.svg
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/Rank.tsx
  src/main.tsx
  src/pages/Mainpage.tsx
  src/pages/NotionAdd.tsx
  src/pages/Ranking_page.tsx
Labels: 퍼블리싱

#43 Design/#38
  src/App.tsx
  src/assets/icon_more.svg
  src/components/Button.tsx
  src/components/CommentItem.tsx
  src/components/SearchUser_item.tsx
  src/pages/CommentPage.tsx
Labels: 퍼블리싱

#45 fix: 테일윈드 버그 수정 (theme object 내로 옵션 이동)
  tailwind.config.js
Labels: 오류수정

#53 feature: 위치 설정 페이지 기능 구현
  src/components/Header.tsx
  src/pages/KakaoMap.tsx
  src/pages/LocationSetting.tsx
Labels: 기능구현

#51 feature: 알림 페이지 기능 구현
  src/components/NotificationItem.tsx
  src/pages/NotificationPage.tsx
Labels: 기능구현

#54 [feature]메인페이지 인기포스터/종목 렌더링
  package.json
  src/App.tsx
  src/components/Health_post.tsx
  src/components/Popular_sports.tsx
  src/pages/Mainpage.tsx
  yarn.lock
Labels: 기능구현

#56 [Feature]로그인 회원가입
  package.json
  src/App.tsx
  src/components/RegisterInput.tsx
  src/data/store.ts
  src/main.tsx
  src/pages/Mainpage.tsx
  src/pages/register/Login.tsx
  src/pages/register/Register.tsx
  yarn.lock
Labels: 기능구현
